version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'fix'
      include: 'scope'
    allow:
      # Allow updates for these packages
      - dependency-name: 'babel-plugin-macros'
