name: CI
on:
  pull_request_target:
    branches:
      - main
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build

      - name: Prepare End To End test with Create React App
        run: |
          - name: Create symlink for vtx-react-scripts
        run: |
          npm link
          npx create-react-app my-app --template typescript
          cd my-app
          npm link environment-enforcer.macro
          npx ts-node ../e2eRunner/createTestCase.ts
          npm run start
      - name: Run End To End Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: "${{ env.MFE_NAME }}/cypress"
          wait-on: "https://localhost:9001/${{ env.MFE_NAME }}.js"
          start: npm run start:${{ env.NODE_ENV }}
          command: npm run cypress:run:e2e:${{ env.NODE_ENV }}
          install: false
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0